In [4]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/Data_Science_Fundamentals/DSF_Project'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/Data_Science_Fundamentals/DSF_Project


In [5]:
%cd '/content/gdrive/MyDrive/Data_Science_Fundamentals/DSF_Project'

/content/gdrive/MyDrive/Data_Science_Fundamentals/DSF_Project


In [6]:
import pandas as pd
import numpy as np

In [ ]:
delay_with_weather = pd.read_csv('Delay_With_Weather_2018-2019.csv')
delay_with_weather

MONTH  DAY_OF_MONTH OP_UNIQUE_CARRIER  ... WT05_Dest  WT07_Dest  WT10_Dest
0            1            14                9E  ...       0.0        0.0        0.0
1            1             2                9E  ...       0.0        0.0        0.0
2            1             2                9E  ...       0.0        0.0        0.0
3            1             2                9E  ...       0.0        0.0        0.0
4            1             3                9E  ...       0.0        0.0        0.0
...        ...           ...               ...  ...       ...        ...        ...
4713645     12            31                B6  ...       0.0        0.0        0.0
4713646     12            31                B6  ...       0.0        0.0        0.0
4713647     12            31                B6  ...       0.0        0.0        0.0
4713648     12            31                B6  ...       0.0        0.0        0.0
4713649     12            31                B6  ...       0.0        0.0        0.0

[4713650 rows x 58 columns]

In [ ]:
delay_with_weather.isna().sum()

MONTH                       0
DAY_OF_MONTH                0
OP_UNIQUE_CARRIER           0
TAIL_NUM                10869
OP_CARRIER_FL_NUM           0
ORIGIN_AIRPORT_ID           0
ORIGIN                      0
ORIGIN_STATE_NM             0
DEST_AIRPORT_ID             0
DEST_AIRPORT_SEQ_ID         0
DEST                        0
DEST_STATE_NM               0
CRS_DEP_TIME                0
DEP_TIME                69719
DEP_DELAY_NEW           70479
DEP_TIME_BLK                0
TAXI_OUT                72177
WHEELS_OFF              72177
WHEELS_ON               73608
TAXI_IN                 73608
CRS_ARR_TIME                0
ARR_TIME                73607
ARR_DELAY_NEW           84781
ARR_TIME_BLK                0
CANCELLED                   0
DIVERTED                    0
TMAX                   146990
TMIN                   146990
PRCP                   146990
SNOW                   146990
SNWD                   146990
AWND                   146990
WT01                   146990
WT08      

In [ ]:
delay_with_weather = delay_with_weather[delay_with_weather['ARR_DELAY_NEW'].notnull()].reset_index(drop=True)
delay_with_weather = delay_with_weather[delay_with_weather['DEP_DELAY_NEW'].notnull()].reset_index(drop=True)
delay_with_weather = delay_with_weather[delay_with_weather['TMAX'].notnull()].reset_index(drop=True)
delay_with_weather = delay_with_weather[delay_with_weather['TMAX_Dest'].notnull()].reset_index(drop=True)
delay_with_weather

MONTH  DAY_OF_MONTH OP_UNIQUE_CARRIER  ... WT05_Dest  WT07_Dest  WT10_Dest
0            1            14                9E  ...       0.0        0.0        0.0
1            1             2                9E  ...       0.0        0.0        0.0
2            1             2                9E  ...       0.0        0.0        0.0
3            1             2                9E  ...       0.0        0.0        0.0
4            1             3                9E  ...       0.0        0.0        0.0
...        ...           ...               ...  ...       ...        ...        ...
4342246     12            31                B6  ...       0.0        0.0        0.0
4342247     12            31                B6  ...       0.0        0.0        0.0
4342248     12            31                B6  ...       0.0        0.0        0.0
4342249     12            31                B6  ...       0.0        0.0        0.0
4342250     12            31                B6  ...       0.0        0.0        0.0

[4342251 rows x 58 columns]

In [ ]:
delay_with_weather.isna().sum()

MONTH                  0
DAY_OF_MONTH           0
OP_UNIQUE_CARRIER      0
TAIL_NUM               0
OP_CARRIER_FL_NUM      0
ORIGIN_AIRPORT_ID      0
ORIGIN                 0
ORIGIN_STATE_NM        0
DEST_AIRPORT_ID        0
DEST_AIRPORT_SEQ_ID    0
DEST                   0
DEST_STATE_NM          0
CRS_DEP_TIME           0
DEP_TIME               0
DEP_DELAY_NEW          0
DEP_TIME_BLK           0
TAXI_OUT               0
WHEELS_OFF             0
WHEELS_ON              0
TAXI_IN                0
CRS_ARR_TIME           0
ARR_TIME               0
ARR_DELAY_NEW          0
ARR_TIME_BLK           0
CANCELLED              0
DIVERTED               0
TMAX                   0
TMIN                   0
PRCP                   0
SNOW                   0
SNWD                   0
AWND                   0
WT01                   0
WT08                   0
WT02                   0
WT04                   0
WT09                   0
WT03                   0
WT06                   0
WT05                   0


In [ ]:
columns =  ['MONTH', 'DAY_OF_MONTH', 'OP_UNIQUE_CARRIER', 'TAIL_NUM','OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID',
      'ORIGIN_STATE_NM','DEST_AIRPORT_ID', 'DEST_STATE_NM', 'CRS_DEP_TIME',
      'DEP_TIME', 'DEP_DELAY_NEW', 'DEP_TIME_BLK', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON',
      'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY_NEW', 'ARR_TIME_BLK', 'CANCELLED', 'DIVERTED', 
      'SNOW', 'SNWD', 'AWND', 'WT01', 'WT02', 'WT03', 'WT04', 'WT06', 'WT07', 'WT08',
      'SNOW_Dest', 'SNWD_Dest', 'AWND_Dest', 'WT01_Dest', 'WT02_Dest', 'WT03_Dest', 'WT04_Dest', 'WT06_Dest', 'WT07_Dest', 'WT08_Dest']

In [ ]:
delay_with_weather = delay_with_weather[columns]
delay_with_weather

MONTH  DAY_OF_MONTH OP_UNIQUE_CARRIER  ... WT06_Dest  WT07_Dest  WT08_Dest
0            1            14                9E  ...       0.0        0.0        0.0
1            1             2                9E  ...       0.0        0.0        0.0
2            1             2                9E  ...       0.0        0.0        0.0
3            1             2                9E  ...       0.0        0.0        0.0
4            1             3                9E  ...       0.0        0.0        0.0
...        ...           ...               ...  ...       ...        ...        ...
4342246     12            31                B6  ...       0.0        0.0        0.0
4342247     12            31                B6  ...       0.0        0.0        1.0
4342248     12            31                B6  ...       0.0        0.0        1.0
4342249     12            31                B6  ...       0.0        0.0        1.0
4342250     12            31                B6  ...       0.0        0.0        1.0

[4342251 rows x 43 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
#le.fit(classification_flight_delay.stack().unique()

delay_with_weather['OP_UNIQUE_CARRIER'] = le.fit_transform(delay_with_weather['OP_UNIQUE_CARRIER'])
delay_with_weather['TAIL_NUM'] = le.fit_transform(delay_with_weather['TAIL_NUM'])

#classification_flight_delay['ORIGIN'] = le.fit_transform(classification_flight_delay['ORIGIN'])
#classification_flight_delay['ORIGIN_CITY_NAME'] = le.fit_transform(classification_flight_delay['ORIGIN_CITY_NAME'])
delay_with_weather['ORIGIN_STATE_NM'] = le.fit_transform(delay_with_weather['ORIGIN_STATE_NM'])

#classification_flight_delay['DEST'] = le.fit_transform(classification_flight_delay['DEST'])
#classification_flight_delay['DEST_CITY_NAME'] = le.fit_transform(classification_flight_delay['DEST_CITY_NAME'])
delay_with_weather['DEST_STATE_NM'] = le.fit_transform(delay_with_weather['DEST_STATE_NM'])

delay_with_weather['DEP_TIME_BLK'] = le.fit_transform(delay_with_weather['DEP_TIME_BLK'])
delay_with_weather['ARR_TIME_BLK'] = le.fit_transform(delay_with_weather['ARR_TIME_BLK'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-do

In [ ]:
delay_with_weather.to_csv("Preprocessed_Flight_Delay.csv",index=False)

In [7]:
delay_with_weather = pd.read_csv("Preprocessed_Flight_Delay.csv")
delay_with_weather

MONTH  DAY_OF_MONTH  ...  WT07_Dest  WT08_Dest
0            1            14  ...        0.0        0.0
1            1             2  ...        0.0        0.0
2            1             2  ...        0.0        0.0
3            1             2  ...        0.0        0.0
4            1             3  ...        0.0        0.0
...        ...           ...  ...        ...        ...
4342246     12            31  ...        0.0        0.0
4342247     12            31  ...        0.0        1.0
4342248     12            31  ...        0.0        1.0
4342249     12            31  ...        0.0        1.0
4342250     12            31  ...        0.0        1.0

[4342251 rows x 43 columns]

In [8]:
def rmspe(true, pred):
    rmspe = np.sqrt(np.mean(((true - pred)/true)**2))
    return rmspe

In [6]:
columns_flight =  ['MONTH', 'DAY_OF_MONTH', 'OP_UNIQUE_CARRIER', 'TAIL_NUM','OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID',
      'ORIGIN_STATE_NM','DEST_AIRPORT_ID', 'DEST_STATE_NM', 'CRS_DEP_TIME',
      'DEP_TIME', 'DEP_DELAY_NEW', 'DEP_TIME_BLK', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON',
      'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY_NEW', 'ARR_TIME_BLK', 'CANCELLED', 'DIVERTED',]

In [7]:
flight_delay = delay_with_weather[columns_flight]
flight_delay

MONTH  DAY_OF_MONTH  ...  CANCELLED  DIVERTED
0            1            14  ...        0.0       0.0
1            1             2  ...        0.0       0.0
2            1             2  ...        0.0       0.0
3            1             2  ...        0.0       0.0
4            1             3  ...        0.0       0.0
...        ...           ...  ...        ...       ...
4342246     12            31  ...        0.0       0.0
4342247     12            31  ...        0.0       0.0
4342248     12            31  ...        0.0       0.0
4342249     12            31  ...        0.0       0.0
4342250     12            31  ...        0.0       0.0

[4342251 rows x 23 columns]

In [11]:
X = flight_delay.drop('ARR_DELAY_NEW', axis=1)
X = X.drop('DEP_DELAY_NEW', axis=1)
y = flight_delay['ARR_DELAY_NEW']
y = y+1

In [12]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import xgboost as xgb
from xgboost import XGBRegressor
import datetime
time_start = datetime.datetime.now()
XGboost_1 = xgb.XGBRegressor(objective='reg:squarederror').fit(X_train,y_train)
time_end = datetime.datetime.now()
print("Time: ", (time_end - time_start))

Time:  0:12:20.567629


In [ ]:
import pickle
file_1 = 'XGboost_Flight_1.sav'
pickle.dump(XGboost_1, open(file_1, 'wb'))

NameError: ignored

In [ ]:
y_pred_xgb_1 = XGboost_1.predict(X_test)
y_pred_xgb_1

array([ 4.0414677,  5.8953257, 22.674255 , ..., 13.504853 ,  5.385741 ,
        6.510045 ], dtype=float32)

In [ ]:
rmspe(y_test, y_pred_xgb_1)

5.600181639394967

In [13]:
import pickle

In [14]:
XGboost_loaded_1 = pickle.load(open('XGboost_Flight_1.sav', 'rb'))
y_pred_xgb_1 = XGboost_loaded_1.predict(X_test)

In [15]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test, y_pred=y_pred_xgb_1, squared=True)
rmse = mean_squared_error(y_true=y_test, y_pred=y_pred_xgb_1, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test, y_pred_xgb_1))

MSE:  555.5961524094505
RMSE:  23.57108721313997
R2 Score:  0.742092950113728


In [22]:
from sklearn import linear_model
lr_1 = linear_model.LinearRegression()

In [23]:
lr_1.fit(X_train,y_train)

LinearRegression()

In [24]:
import pickle
file_1_1 = 'LR_Flight.sav'
pickle.dump(lr_1, open(file_1_1, 'wb'))

In [25]:
y_pred_lr_2 = lr_1.predict(X_test)

In [26]:
rmspe(y_test, y_pred_lr_2)

10.928456922223086

In [27]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_lr_2)

0.08356386428593676

In [28]:
lr_loaded = pickle.load(open('LR_Flight.sav', 'rb'))
y_pred_lr_2 = lr_loaded.predict(X_test)
rmspe(y_test, y_pred_lr_2)

10.928456922223086

In [30]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test, y_pred=y_pred_lr_2, squared=True)
rmse = mean_squared_error(y_true=y_test, y_pred=y_pred_lr_2, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test, y_pred_lr_2))

MSE:  1974.2321551746804
RMSE:  44.43233231752167
R2 Score:  0.08356386428593676


In [ ]:
import xgboost as xgb
from xgboost import XGBRegressor
XGboost_2 = xgb.XGBRegressor(objective='reg:squarederror', colsample_bytree = 0.4, learning_rate=0.08,
                        max_depth=5, alpha=10, n_estimators=150).fit(X_train,y_train)

In [ ]:
import pickle
file_2 = 'XGboost_Flight_2.sav'
pickle.dump(XGboost_2, open(file_2, 'wb'))

In [ ]:
y_pred_xgb_2 = XGboost_2.predict(X_test)
y_pred_xgb_2

array([ 3.1157243,  2.9735742, 13.404963 , ..., 11.343515 ,  4.480937 ,
        1.4429889], dtype=float32)

In [ ]:
rmspe(y_test, y_pred_xgb_2)

3.353766655376825

In [16]:
XGboost_loaded_2 = pickle.load(open('XGboost_Flight_2.sav', 'rb'))
y_pred_xgb_2 = XGboost_loaded_2.predict(X_test)
rmspe(y_test, y_pred_xgb_2)

3.353766655376825

In [17]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test, y_pred=y_pred_xgb_2, squared=True)
rmse = mean_squared_error(y_true=y_test, y_pred=y_pred_xgb_2, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test, y_pred_xgb_2))

MSE:  151.67942441926408
RMSE:  12.315820087158796
R2 Score:  0.9295905979356189


In [ ]:
import xgboost as xgb
from xgboost import XGBRegressor
XGboost_3 = xgb.XGBRegressor(objective='reg:squarederror', colsample_bytree = 0.4, learning_rate=0.1,
                        max_depth=5, alpha=10, n_estimators=300).fit(X_train,y_train)

In [ ]:
import pickle
file_3 = 'XGboost_Flight_3.sav'
pickle.dump(XGboost_3, open(file_3, 'wb'))

In [ ]:
y_pred_xgb_3 = XGboost_3.predict(X_test)
y_pred_xgb_3

array([ 0.9932423 ,  0.8030057 , 14.878996  , ..., 10.574622  ,
        2.944728  ,  0.63639694], dtype=float32)

In [ ]:
rmspe(y_test, y_pred_xgb_3)

2.3254642641601717

In [19]:
XGboost_loaded_3 = pickle.load(open('XGboost_Flight_3.sav', 'rb'))
y_pred_xgb_3 = XGboost_loaded_3.predict(X_test)
rmspe(y_test, y_pred_xgb_3)

2.3254642641601717

In [20]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test, y_pred=y_pred_xgb_3, squared=True)
rmse = mean_squared_error(y_true=y_test, y_pred=y_pred_xgb_3, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test, y_pred_xgb_3))

MSE:  87.19645567111398
RMSE:  9.337904244053586
R2 Score:  0.9595235126356617


In [9]:
X_weather = delay_with_weather.drop('ARR_DELAY_NEW', axis=1)
X_weather = X_weather.drop('DEP_DELAY_NEW', axis=1)
y_weather = delay_with_weather['ARR_DELAY_NEW']
y_weather = y_weather+1

In [10]:
import sklearn
from sklearn.model_selection import train_test_split
X_train_weather, X_test_weather, y_train_weather, y_test_weather = train_test_split(X_weather, y_weather, test_size=0.2, random_state=42)

In [20]:
import xgboost as xgb
from xgboost import XGBRegressor
import datetime
time_start = datetime.datetime.now()
XGboost_weather_1 = xgb.XGBRegressor(objective='reg:squarederror').fit(X_train_weather,y_train_weather)
time_end = datetime.datetime.now()
print("Time: ", (time_end - time_start))

Time:  0:15:36.359284


In [23]:
import pickle
file_4 = 'XGboost_Flight_Weather_1.sav'
pickle.dump(XGboost_weather_1, open(file_4, 'wb'))

In [21]:
y_pred_xgb_weather_1 = XGboost_weather_1.predict(X_test_weather)
y_pred_xgb_weather_1

array([ 2.6614373,  6.953503 , 31.691021 , ..., 15.730562 , 11.879987 ,
        6.494712 ], dtype=float32)

In [22]:
rmspe(y_test_weather, y_pred_xgb_weather_1)

5.9422585968405555

In [34]:
XGboost_weather_loaded_1 = pickle.load(open('XGboost_Flight_Weather_1.sav', 'rb'))
y_pred_xgb_weather_1 = XGboost_weather_loaded_1.predict(X_test_weather)
rmspe(y_test_weather, y_pred_xgb_weather_1)

5.9422585968405555

In [35]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_xgb_weather_1, squared=True)
rmse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_xgb_weather_1, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test_weather, y_pred_xgb_weather_1))

MSE:  547.4925542840316
RMSE:  23.398558807841813
R2 Score:  0.7458546303862194


In [14]:
from sklearn import linear_model
lr_weather = linear_model.LinearRegression()

In [15]:
lr_weather.fit(X_train_weather,y_train_weather)

LinearRegression()

In [20]:
import pickle
file_1_4 = 'LR_Flight_Weather.sav'
pickle.dump(lr_weather, open(file_1_4, 'wb'))

In [21]:
y_pred_lr = lr_weather.predict(X_test_weather)

In [22]:
rmspe(y_test_weather, y_pred_lr)

11.334511774101667

In [23]:
from sklearn.metrics import r2_score
r2_score(y_test_weather, y_pred_lr_1)

0.10578143606262436

In [12]:
import pickle
lr_weather_loaded = pickle.load(open('LR_Flight_Weather.sav', 'rb'))
y_pred_lr = lr_weather_loaded.predict(X_test_weather)
rmspe(y_test_weather, y_pred_lr)

11.334511774101667

In [13]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_lr, squared=True)
rmse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_lr, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test_weather, y_pred_lr))

MSE:  1926.369960634238
RMSE:  43.89043131064262
R2 Score:  0.10578143606262436


In [8]:
import xgboost as xgb
from xgboost import XGBRegressor
import datetime
time_start = datetime.datetime.now()
XGboost_weather_2 = xgb.XGBRegressor(objective='reg:squarederror', colsample_bytree = 0.4, learning_rate=0.08,
                        max_depth=5, alpha=10, n_estimators=150).fit(X_train_weather,y_train_weather)
time_end = datetime.datetime.now()
print("Time: ", (time_end - time_start))

Time:  0:19:24.585454


In [25]:
import pickle
file_5 = 'XGboost_Flight_Weather_2.sav'
pickle.dump(XGboost_weather_2, open(file_5, 'wb'))

In [9]:
y_pred_xgb_weather_2 = XGboost_weather_2.predict(X_test_weather)
y_pred_xgb_weather_2

array([ 2.2030454,  3.0263104, 28.52284  , ..., 14.29997  ,  4.1646643,
        1.8912277], dtype=float32)

In [10]:
rmspe(y_test_weather, y_pred_xgb_weather_2)

3.555002527553761

In [11]:
from sklearn.metrics import r2_score
r2_score(y_test_weather, y_pred_xgb_weather_2)

0.9224426934988094

In [36]:
XGboost_weather_loaded_2 = pickle.load(open('XGboost_Flight_Weather_2.sav', 'rb'))
y_pred_xgb_weather_2 = XGboost_weather_loaded_2.predict(X_test_weather)
rmspe(y_test_weather, y_pred_xgb_weather_2)

3.555002527553761

In [37]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_xgb_weather_2, squared=True)
rmse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_xgb_weather_2, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test_weather, y_pred_xgb_weather_2))

MSE:  167.07779450892644
RMSE:  12.925857592783794
R2 Score:  0.9224426934988094


In [27]:
import xgboost as xgb
from xgboost import XGBRegressor
import datetime
time_start = datetime.datetime.now()
XGboost_weather_3 = xgb.XGBRegressor(objective='reg:squarederror', colsample_bytree = 0.4, learning_rate=0.1,
                        max_depth=5, alpha=10, n_estimators=300).fit(X_train_weather,y_train_weather)
time_end = datetime.datetime.now()
print("Time: ", (time_end - time_start))

Time:  0:39:51.789544


In [33]:
import pickle
file_6 = 'XGboost_Flight_Weather_3.sav'
pickle.dump(XGboost_weather_3, open(file_6, 'wb'))

In [34]:
y_pred_xgb_weather_3 = XGboost_weather_3.predict(X_test_weather)
y_pred_xgb_weather_3

array([ 1.0904262 ,  0.31102175, 18.352192  , ...,  9.456421  ,
        2.0138116 ,  0.57987577], dtype=float32)

In [35]:
rmspe(y_test_weather, y_pred_xgb_weather_3)

2.3798144150716953

In [38]:
XGboost_weather_loaded_3 = pickle.load(open('XGboost_Flight_Weather_3.sav', 'rb'))
y_pred_xgb_weather_3 = XGboost_weather_loaded_3.predict(X_test_weather)
rmspe(y_test_weather, y_pred_xgb_weather_3)

2.3798144150716953

In [39]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_xgb_weather_3, squared=True)
rmse = mean_squared_error(y_true=y_test_weather, y_pred=y_pred_xgb_weather_3, squared=False)
print("MSE: ", mse)
print("RMSE: ", rmse)
print("R2 Score: ", r2_score(y_test_weather, y_pred_xgb_weather_3))

MSE:  99.6193466428461
RMSE:  9.980949185465583
R2 Score:  0.9537568219419201


In [41]:
delay_with_weather.loc[delay_with_weather['ARR_DELAY_NEW'] > 0, 'ARR_DELAY_NEW_2'] = 1
delay_with_weather.loc[delay_with_weather['ARR_DELAY_NEW'] <= 0, 'ARR_DELAY_NEW_2'] = 0

In [42]:
delay_with_weather['ARR_DELAY_NEW_2'].sort_values(ascending=False).value_counts()

0.0    2743579
1.0    1598672
Name: ARR_DELAY_NEW_2, dtype: int64

In [43]:
delay_minority = delay_with_weather[delay_with_weather.ARR_DELAY_NEW_2==1]
delay_majority = delay_with_weather[delay_with_weather.ARR_DELAY_NEW_2==0]

In [44]:
delay_minority

MONTH  DAY_OF_MONTH  ...  WT08_Dest  ARR_DELAY_NEW_2
1            1             2  ...        0.0              1.0
4            1             3  ...        0.0              1.0
5            1             5  ...        0.0              1.0
6            1             6  ...        0.0              1.0
7            1             9  ...        0.0              1.0
...        ...           ...  ...        ...              ...
4342237     12            31  ...        0.0              1.0
4342241     12            31  ...        0.0              1.0
4342242     12            31  ...        0.0              1.0
4342243     12            31  ...        0.0              1.0
4342244     12            31  ...        0.0              1.0

[1598672 rows x 44 columns]

In [45]:
from sklearn.utils import resample
delay_majority_downsampled = resample(delay_majority, replace=True, n_samples=1598672, random_state=42)
delay_downsampled = pd.concat([delay_minority, delay_majority_downsampled])

In [46]:
delay_downsampled['ARR_DELAY_NEW_2'].sort_values(ascending=False).value_counts()

1.0    1598672
0.0    1598672
Name: ARR_DELAY_NEW_2, dtype: int64

In [47]:
delay_downsampled = delay_downsampled.drop('ARR_DELAY_NEW_2', axis=1)
delay_downsampled.reset_index(drop=True)

MONTH  DAY_OF_MONTH  ...  WT07_Dest  WT08_Dest
0            1             2  ...        0.0        0.0
1            1             3  ...        0.0        0.0
2            1             5  ...        0.0        0.0
3            1             6  ...        0.0        0.0
4            1             9  ...        0.0        0.0
...        ...           ...  ...        ...        ...
3197339      1            28  ...        0.0        0.0
3197340      5             4  ...        0.0        0.0
3197341      1            28  ...        0.0        0.0
3197342      3            22  ...        0.0        0.0
3197343      6            15  ...        0.0        1.0

[3197344 rows x 43 columns]

In [6]:
delay_with_weather.loc[delay_with_weather['ARR_DELAY_NEW'] > 0, 'ARR_DELAY_NEW_2'] = 1
delay_with_weather.loc[delay_with_weather['ARR_DELAY_NEW'] <= 0, 'ARR_DELAY_NEW_2'] = 0

In [7]:
delay_with_weather['ARR_DELAY_NEW_2'].sort_values(ascending=False).value_counts()

0.0    2743579
1.0    1598672
Name: ARR_DELAY_NEW_2, dtype: int64

In [8]:
delay_minority = delay_with_weather[delay_with_weather.ARR_DELAY_NEW_2==1]
delay_majority = delay_with_weather[delay_with_weather.ARR_DELAY_NEW_2==0]

In [9]:
delay_majority

MONTH  DAY_OF_MONTH  ...  WT08_Dest  ARR_DELAY_NEW_2
0            1            14  ...        0.0              0.0
2            1             2  ...        0.0              0.0
3            1             2  ...        0.0              0.0
10           1            13  ...        0.0              0.0
11           1            14  ...        0.0              0.0
...        ...           ...  ...        ...              ...
4342246     12            31  ...        0.0              0.0
4342247     12            31  ...        1.0              0.0
4342248     12            31  ...        1.0              0.0
4342249     12            31  ...        1.0              0.0
4342250     12            31  ...        1.0              0.0

[2743579 rows x 44 columns]

In [10]:
from sklearn.utils import resample
delay_minority_upsampled = resample(delay_minority, replace=True, n_samples=2743579, random_state=42)
delay_upsampled = pd.concat([delay_majority, delay_minority_upsampled])

In [11]:
delay_upsampled['ARR_DELAY_NEW_2'].sort_values(ascending=False).value_counts()

1.0    2743579
0.0    2743579
Name: ARR_DELAY_NEW_2, dtype: int64

In [12]:
X = delay_upsampled.drop('ARR_DELAY_NEW', axis=1)
X = X.drop('DEP_DELAY_NEW', axis=1)
y = delay_upsampled['ARR_DELAY_NEW']
y = y+1

In [13]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import xgboost as xgb
from xgboost import XGBRegressor
import datetime
time_start = datetime.datetime.now()
XGboost_1 = xgb.XGBRegressor(objective='reg:squarederror').fit(X_train,y_train)
time_end = datetime.datetime.now()
print("Time: ", (time_end - time_start))

In [ ]:
def rmspe(true, pred):
    rmspe = np.sqrt(np.mean(((true - pred)/true)**2))
    return rmspe